// AUTO-GENERATED BY RUST GENERATOR
// DO NOT EDIT MANUALLY

#ifndef DATABASE_CONSTANTS_H
#define DATABASE_CONSTANTS_H

#include <stdint.h>

// =========================================
// OMNI_SEARCH
// =========================================
#define OMNI_SEARCH_TOTAL_ROW_SIZE 32ULL
#define OMNI_SEARCH_TERM_SIZE 24ULL
#define OMNI_SEARCH_CHUNK_SIZE_ROWS 256ULL
#define OMNI_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define OMNI_SEARCH_TOP_LEVEL_ROWS 39ULL

// =========================================
// TEMPORAL_SEARCH
// =========================================
#define TEMPORAL_SEARCH_TOTAL_ROW_SIZE 16ULL
#define TEMPORAL_SEARCH_TERM_SIZE 8ULL
#define TEMPORAL_SEARCH_CHUNK_SIZE_ROWS 512ULL
#define TEMPORAL_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define TEMPORAL_SEARCH_TOP_LEVEL_ROWS 3ULL

// =========================================
// ASTRONOMICAL_SEARCH
// =========================================
#define ASTRONOMICAL_SEARCH_TOTAL_ROW_SIZE 16ULL
#define ASTRONOMICAL_SEARCH_TERM_SIZE 8ULL
#define ASTRONOMICAL_SEARCH_CHUNK_SIZE_ROWS 512ULL
#define ASTRONOMICAL_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define ASTRONOMICAL_SEARCH_TOP_LEVEL_ROWS 1ULL

// =========================================
// GLOBE_COORDINATE_SEARCH
// =========================================
#define GLOBE_COORDINATE_SEARCH_TOTAL_ROW_SIZE 16ULL
#define GLOBE_COORDINATE_SEARCH_TERM_SIZE 8ULL
#define GLOBE_COORDINATE_SEARCH_CHUNK_SIZE_ROWS 512ULL
#define GLOBE_COORDINATE_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define GLOBE_COORDINATE_SEARCH_TOP_LEVEL_ROWS 2ULL

// =========================================
// WIKI_PDA_ENABLE
// =========================================
#define WIKI_PDA_ENABLE_OMNI_SEARCH 1
#define WIKI_PDA_ENABLE_TEMPORAL_SEARCH 1
#define WIKI_PDA_ENABLE_ASTRONOMICAL_SEARCH 1
#define WIKI_PDA_ENABLE_GLOBE_COORDINATE_SEARCH 1

// =========================================
// OFFSETS
// =========================================
#define OFFSETS_PID_INDEX 663552ULL
#define OFFSETS_QID_INDEX 457728ULL
#define OFFSETS_QID_HASHMAP 356352ULL
#define OFFSETS_PID_STRINGS 663552ULL
#define OFFSETS_PID_HASHMAP 663040ULL
#define OFFSETS_TITLES 587264ULL
#define OFFSETS_CONTENT 664064ULL
#define OFFSETS_ZSTD_DICTIONARY 96878080ULL
#define OFFSETS_METADATA 95709184ULL

static const uint64_t OFFSETS_GLOBE_COORDINATE_SEARCH_LEVEL[] = {
    320512ULL,	// level_0
    335360ULL,	// level_1
};


static const uint64_t OFFSETS_OMNI_SEARCH_LEVEL[] = {
    0ULL,	// level_0
    318976ULL,	// level_1
};


static const uint64_t OFFSETS_TEMPORAL_SEARCH_LEVEL[] = {
    336896ULL,	// level_0
    355840ULL,	// level_1
};


static const uint64_t OFFSETS_ASTRONOMICAL_SEARCH_LEVEL[] = {
    335872ULL,	// level_0
    336384ULL,	// level_1
};


// =========================================
// SIZES
// =========================================
#define SIZES_PID_INDEX 0ULL
#define SIZES_QID_INDEX 129348ULL
#define SIZES_QID_HASHMAP 101202ULL
#define SIZES_PID_STRINGS 1ULL
#define SIZES_PID_HASHMAP 6ULL
#define SIZES_TITLES 75487ULL
#define SIZES_CONTENT 95045053ULL
#define SIZES_ZSTD_DICTIONARY 32768ULL
#define SIZES_METADATA 1168786ULL

static const uint64_t SIZES_ASTRONOMICAL_SEARCH_LEVEL[] = {
    272ULL,	// level_0
    16ULL,	// level_1
};


static const uint64_t SIZES_OMNI_SEARCH_LEVEL[] = {
    318720ULL,	// level_0
    1248ULL,	// level_1
};


static const uint64_t SIZES_TEMPORAL_SEARCH_LEVEL[] = {
    18544ULL,	// level_0
    48ULL,	// level_1
};


static const uint64_t SIZES_GLOBE_COORDINATE_SEARCH_LEVEL[] = {
    14704ULL,	// level_0
    32ULL,	// level_1
};


#endif // DATABASE_CONSTANTS_H
