/**
 * @file wiki_pda_options.h
 * @brief User-configurable options for the Wiki PDA library.
 *
 * This file contains macros that tune the memory footprint and performance
 * of the database queries. You can modify these values directly here or
 * override them via your build system (e.g., using -D compiler flags)
 * without altering the library source code.
 */

#ifndef WIKI_PDA_OPTIONS_H
#define WIKI_PDA_OPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// Version specific constants (Do not change)
// ============================================================================

// ----------------------------------------------------------------------------
// Database Versioning
// Defines the required version of the generated binary files. The API will 
// reject databases generated by incompatible versions of the Rust tool.
// ----------------------------------------------------------------------------
#define SUPPORT_MAJOR_VERSION 0
#define SUPPORT_MINOR_VERSION 1

// ----------------------------------------------------------------------------
// Index & File Geometry
// WARNING: Modifying these values will break binary compatibility. They must 
// strictly match the Rust generator (src/wiki_pda_tool/src/utils/constants.rs).
// ----------------------------------------------------------------------------

// The absolute maximum depth of the sparse index tree. Prevents infinite loops 
// or buffer overflows during deep index traversal.
#define MAX_SPARSE_LEVELS 15

// Standard SD card block size in bytes. Used to ensure optimal, block-aligned 
// hardware I/O reads from the storage medium.
#define SD_SECTOR_SIZE 512

// The fixed amount of reserved space (in bytes) at the start of the binary 
// files before the actual row data begins.
#define HEADER_SIZE_BYTES 4096

// The allocated byte length for the text string in the Omni Search index.
// MATH RULE: Must equal (PowerOfTwo - 8) so the total row size aligns perfectly 
// in memory (Term Size + 4-byte QID + 4-byte Tag Mask). 
// Example: 56 + 4 + 4 = 64 bytes per row.
#define OMNI_SEARCH_TERM_SIZE 56

// ----------------------------------------------------------------------------
// File Validation
// ----------------------------------------------------------------------------

// The magic string and its length expected at the very beginning of the header 
// to verify that the file is a valid WikiPDA database.
#define WPDA_MAGIC "WPDA"
#define WPDA_MAGIC_LENGTH 4

// ============================================================================
// FEATURE TOGGLES (INDEX ENABLES)
// ============================================================================
// You can disable specific search indexes by setting these to 0. 
// Disabling unused indexes prevents the associated code from being compiled,
// significantly reducing the flash memory size of your final firmware. This is 
// highly recommended for constrained embedded devices (like ESP32 or Teensy).

/**
 * @brief Enable or disable the Omni (Text) Search functionality.
 * Set to 1 to enable, 0 to disable.
 */
#ifndef WIKI_PDA_ENABLE_OMNI_SEARCH
#define WIKI_PDA_ENABLE_OMNI_SEARCH 1
#endif

/**
 * @brief Enable or disable the Temporal (Time/Date) Search functionality.
 * Set to 1 to enable, 0 to disable.
 */
#ifndef WIKI_PDA_ENABLE_TEMPORAL_SEARCH
#define WIKI_PDA_ENABLE_TEMPORAL_SEARCH 1
#endif

/**
 * @brief Enable or disable the Astronomical (Celestial Coordinates) Search functionality.
 * Set to 1 to enable, 0 to disable.
 */
#ifndef WIKI_PDA_ENABLE_ASTRONOMICAL_SEARCH
#define WIKI_PDA_ENABLE_ASTRONOMICAL_SEARCH 1
#endif

/**
 * @brief Enable or disable the Globe (Earth Coordinates) Search functionality.
 * Set to 1 to enable, 0 to disable.
 */
#ifndef WIKI_PDA_ENABLE_GLOBE_COORDINATE_SEARCH
#define WIKI_PDA_ENABLE_GLOBE_COORDINATE_SEARCH 1
#endif

// ============================================================================
// OMNI SEARCH OPTIONS
// ============================================================================

/**
 * @brief Size of the QID deduplication cache.
 *
 * Used to make sure QIDs are not considered multiple times when searching
 * (specifically for the omni search index). A larger cache prevents duplicate
 * results but consumes more stack/heap memory.
 */
#ifndef MAX_DEDUPLICATION_CACHE
#define MAX_DEDUPLICATION_CACHE 128
#endif

// ============================================================================
// SPATIAL & ASTRONOMICAL SEARCH OPTIONS
// ============================================================================

/**
 * @brief Maximum capacity for sorted spatial search results.
 *
 * Defines the maximum number of results saved when performing sorted spatial
 * queries. This is relevant for both sorted astronomical search and sorted
 * globe coordinate search.
 */
#ifndef MAX_SORTED_RESULTS
#define MAX_SORTED_RESULTS 50
#endif

/**
 * @brief Maximum number of Morton ranges to search.
 *
 * A lower number reduces the number of random reads the database needs to perform,
 * saving overhead on storage media with high latency (like SD cards).
 * Increasing this number will increase the number of sequential reads needed.
 * Relevant for astronomical and globe coordinate search.
 */
#ifndef MAX_MORTON_RANGES
#define MAX_MORTON_RANGES 64
#endif

#ifdef __cplusplus
}
#endif

#endif // WIKI_PDA_OPTIONS_H
