use serde_json::Value;
use std::fs::File;
use std::io::{Read, Write};
use std::path::PathBuf;

use crate::utils::constants;
use crate::utils::settings::Settings;

pub fn make_c_header_file(settings: &Settings) -> Result<(), String> {
    let tmp_dir = PathBuf::from(&settings.paths.tmp_dir);
    let info_json_path = tmp_dir.join(constants::INFO_JSON);
    let header_path = PathBuf::from("./src/wiki_pda_api/src/common/generated_database_constants.h");

    let mut file =
        File::open(&info_json_path).map_err(|e| format!("Failed to open info.json: {}", e))?;
    let mut json_str = String::new();
    file.read_to_string(&mut json_str)
        .map_err(|e| e.to_string())?;

    let json_val: Value =
        serde_json::from_str(&json_str).map_err(|e| format!("Invalid JSON: {}", e))?;
    let root_obj = json_val
        .as_object()
        .ok_or("info.json root is not a JSON object")?;

    let mut out_file = File::create(&header_path).map_err(|e| e.to_string())?;

    writeln!(out_file, "// AUTO-GENERATED BY RUST GENERATOR")
        .and_then(|_| writeln!(out_file, "// DO NOT EDIT MANUALLY\n"))
        .and_then(|_| writeln!(out_file, "#ifndef DATABASE_CONSTANTS_H"))
        .and_then(|_| writeln!(out_file, "#define DATABASE_CONSTANTS_H\n"))
        .and_then(|_| writeln!(out_file, "#include <stdint.h>\n"))
        .map_err(|e| e.to_string())?;

    for (category, inner_val) in root_obj {
        if let Some(inner_obj) = inner_val.as_object() {
            writeln!(out_file, "// =========================================")
                .map_err(|e| e.to_string())?;
            writeln!(out_file, "// {}", category.to_uppercase()).map_err(|e| e.to_string())?;
            writeln!(out_file, "// =========================================")
                .map_err(|e| e.to_string())?;

            for (key, value) in inner_obj {
                let macro_name = format!("{}_{}", category, key).to_uppercase();

                match value {
                    Value::Number(n) => {
                        writeln!(out_file, "#define {} {}ULL", macro_name, n)
                            .map_err(|e| e.to_string())?;
                    }
                    Value::String(s) => {
                        writeln!(out_file, "#define {} \"{}\"", macro_name, s)
                            .map_err(|e| e.to_string())?;
                    }
                    Value::Bool(b) => {
                        let bool_val = if *b { "1" } else { "0" };
                        writeln!(out_file, "#define {} {}", macro_name, bool_val)
                            .map_err(|e| e.to_string())?;
                    }

                    Value::Object(dict) => {
                        let mut entries: Vec<_> = dict.iter().collect();

                        entries.sort_by_key(|(k, _)| {
                            k.chars()
                                .filter(|c| c.is_ascii_digit())
                                .collect::<String>()
                                .parse::<u64>()
                                .unwrap_or(0)
                        });

                        writeln!(out_file, "\nstatic const uint64_t {}[] = {{", macro_name)
                            .map_err(|e| e.to_string())?;

                        for (inner_k, inner_v) in entries {
                            let val_str = inner_v
                                .as_u64()
                                .map(|v| format!("{}ULL", v))
                                .unwrap_or_else(|| "0ULL".to_string());

                            writeln!(out_file, "    {},\t// {}", val_str, inner_k)
                                .map_err(|e| e.to_string())?;
                        }

                        writeln!(out_file, "}};\n").map_err(|e| e.to_string())?;
                    }

                    _ => continue,
                };
            }
            writeln!(out_file, "").map_err(|e| e.to_string())?;
        }
    }

    writeln!(out_file, "#endif // DATABASE_CONSTANTS_H").map_err(|e| e.to_string())?;

    println!("Successfully generated C header at {:?}", header_path);

    Ok(())
}
