use serde_json::Value;
use shared::constants;
use shared::load_config::Settings;
use std::fs::File;
use std::io::{Read, Write};
use std::path::PathBuf;

pub fn make_c_header_file(settings: &Settings) -> Result<(), String> {
    // 1. Setup paths
    let tmp_dir = PathBuf::from(&settings.paths.tmp_dir);
    let info_json_path = tmp_dir.join(constants::INFO_JSON);
    let header_path = PathBuf::from("./src/query_database/src/database_constants.h");

    // 2. Read and parse the info.json file
    let mut file =
        File::open(&info_json_path).map_err(|e| format!("Failed to open info.json: {}", e))?;
    let mut json_str = String::new();
    file.read_to_string(&mut json_str)
        .map_err(|e| e.to_string())?;

    let json_val: Value =
        serde_json::from_str(&json_str).map_err(|e| format!("Invalid JSON: {}", e))?;
    let root_obj = json_val
        .as_object()
        .ok_or("info.json root is not a JSON object")?;

    // 3. Open the C header file for writing
    let mut out_file = File::create(&header_path).map_err(|e| e.to_string())?;

    // 4. Write the Header Guards & Includes
    writeln!(out_file, "// AUTO-GENERATED BY RUST GENERATOR")
        .and_then(|_| writeln!(out_file, "// DO NOT EDIT MANUALLY\n"))
        .and_then(|_| writeln!(out_file, "#ifndef DATABASE_CONSTANTS_H"))
        .and_then(|_| writeln!(out_file, "#define DATABASE_CONSTANTS_H\n"))
        .and_then(|_| writeln!(out_file, "#include <stdint.h>\n")) // Needed for uint64_t
        .map_err(|e| e.to_string())?;

    // 5. Iterate through the JSON categories
    for (category, inner_val) in root_obj {
        if let Some(inner_obj) = inner_val.as_object() {
            // Write a nice comment separating sections
            writeln!(out_file, "// =========================================")
                .map_err(|e| e.to_string())?;
            writeln!(out_file, "// {}", category.to_uppercase()).map_err(|e| e.to_string())?;
            writeln!(out_file, "// =========================================")
                .map_err(|e| e.to_string())?;

            for (key, value) in inner_obj {
                // Combine category and key (e.g., OMNI_SEARCH_TOTAL_ROW_SIZE)
                let macro_name = format!("{}_{}", category, key).to_uppercase();

                match value {
                    // Primitive values become #define macros
                    Value::Number(n) => {
                        writeln!(out_file, "#define {} {}", macro_name, n)
                            .map_err(|e| e.to_string())?;
                    }
                    Value::String(s) => {
                        writeln!(out_file, "#define {} \"{}\"", macro_name, s)
                            .map_err(|e| e.to_string())?;
                    }
                    Value::Bool(b) => {
                        let bool_val = if *b { "1" } else { "0" };
                        writeln!(out_file, "#define {} {}", macro_name, bool_val)
                            .map_err(|e| e.to_string())?;
                    }

                    // Nested dictionaries become static const arrays
                    Value::Object(dict) => {
                        let mut entries: Vec<_> = dict.iter().collect();

                        // Sort by numeric value inside the key to ensure level_10 comes after level_2
                        entries.sort_by_key(|(k, _)| {
                            k.chars()
                                .filter(|c| c.is_ascii_digit())
                                .collect::<String>()
                                .parse::<u64>()
                                .unwrap_or(0)
                        });

                        writeln!(out_file, "\nstatic const uint64_t {}[] = {{", macro_name)
                            .map_err(|e| e.to_string())?;

                        for (inner_k, inner_v) in entries {
                            // Default to 0 if the value somehow isn't a number
                            let val_str = inner_v
                                .as_u64()
                                .map(|v| v.to_string())
                                .unwrap_or_else(|| "0".to_string());
                            writeln!(out_file, "    {},\t// {}", val_str, inner_k)
                                .map_err(|e| e.to_string())?;
                        }

                        writeln!(out_file, "}};\n").map_err(|e| e.to_string())?;
                    }

                    // Skip nested arrays for now
                    _ => continue,
                };
            }
            writeln!(out_file, "").map_err(|e| e.to_string())?; // Blank line for spacing
        }
    }

    // 6. Close the Header Guard
    writeln!(out_file, "#endif // DATABASE_CONSTANTS_H").map_err(|e| e.to_string())?;

    println!("Successfully generated C header at {:?}", header_path);

    Ok(())
}
