// AUTO-GENERATED BY RUST GENERATOR
// DO NOT EDIT MANUALLY

#ifndef DATABASE_CONSTANTS_H
#define DATABASE_CONSTANTS_H

#include <stdint.h>

// =========================================
// ASTRONOMICAL_SEARCH
// =========================================
#define ASTRONOMICAL_SEARCH_CHUNK_SIZE_ROWS 512ULL
#define ASTRONOMICAL_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define ASTRONOMICAL_SEARCH_TERM_SIZE 8ULL
#define ASTRONOMICAL_SEARCH_TOP_LEVEL_ROWS 1ULL
#define ASTRONOMICAL_SEARCH_TOTAL_ROW_SIZE 16ULL

// =========================================
// GLOBE_COORDINATE_SEARCH
// =========================================
#define GLOBE_COORDINATE_SEARCH_CHUNK_SIZE_ROWS 512ULL
#define GLOBE_COORDINATE_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define GLOBE_COORDINATE_SEARCH_TERM_SIZE 8ULL
#define GLOBE_COORDINATE_SEARCH_TOP_LEVEL_ROWS 2ULL
#define GLOBE_COORDINATE_SEARCH_TOTAL_ROW_SIZE 16ULL

// =========================================
// OFFSETS
// =========================================
#define OFFSETS_CONTENT 347414ULL
#define OFFSETS_METADATA 46490466ULL

static const uint64_t OFFSETS_OMNI_SEARCH_LEVEL[] = {
    0ULL,	// level_0
    192160ULL,	// level_1
};

#define OFFSETS_QID_HASHMAP 192928ULL
#define OFFSETS_QID_INDEX 294130ULL
#define OFFSETS_ZSTD_DICTIONARY 47646483ULL

// =========================================
// OMNI_SEARCH
// =========================================
#define OMNI_SEARCH_CHUNK_SIZE_ROWS 256ULL
#define OMNI_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define OMNI_SEARCH_TERM_SIZE 24ULL
#define OMNI_SEARCH_TOP_LEVEL_ROWS 24ULL
#define OMNI_SEARCH_TOTAL_ROW_SIZE 32ULL

// =========================================
// SIZES
// =========================================
#define SIZES_CONTENT 46143052ULL
#define SIZES_METADATA 1156017ULL

static const uint64_t SIZES_OMNI_SEARCH_LEVEL[] = {
    192160ULL,	// level_0
    768ULL,	// level_1
};

#define SIZES_QID_HASHMAP 101202ULL
#define SIZES_QID_INDEX 53284ULL
#define SIZES_ZSTD_DICTIONARY 32768ULL

// =========================================
// TEMPORAL_SEARCH
// =========================================
#define TEMPORAL_SEARCH_CHUNK_SIZE_ROWS 512ULL
#define TEMPORAL_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define TEMPORAL_SEARCH_TERM_SIZE 8ULL
#define TEMPORAL_SEARCH_TOP_LEVEL_ROWS 3ULL
#define TEMPORAL_SEARCH_TOTAL_ROW_SIZE 16ULL

#endif // DATABASE_CONSTANTS_H
