// AUTO-GENERATED BY RUST GENERATOR
// DO NOT EDIT MANUALLY

#ifndef DATABASE_CONSTANTS_H
#define DATABASE_CONSTANTS_H

#include <stdint.h>

// =========================================
// OFFSETS
// =========================================
#define OFFSETS_CONTENT 177964ULL
#define OFFSETS_METADATA 27941185ULL

static const uint64_t OFFSETS_OMNI_SEARCH_LEVEL[] = {
    0ULL,	// level_0
    99552ULL,	// level_1
};

#define OFFSETS_QID_HASHMAP 99936ULL
#define OFFSETS_QID_INDEX 150930ULL
#define OFFSETS_ZSTD_DICTIONARY 28547576ULL

// =========================================
// OMNI_SEARCH
// =========================================
#define OMNI_SEARCH_CHUNK_SIZE_ROWS 256ULL
#define OMNI_SEARCH_NUM_SPARSE_LEVELS 1ULL
#define OMNI_SEARCH_TERM_SIZE 24ULL
#define OMNI_SEARCH_TOP_LEVEL_ROWS 12ULL
#define OMNI_SEARCH_TOTAL_ROW_SIZE 32ULL

// =========================================
// SIZES
// =========================================
#define SIZES_CONTENT 27763221ULL
#define SIZES_METADATA 606391ULL

static const uint64_t SIZES_OMNI_SEARCH_LEVEL[] = {
    99552ULL,	// level_0
    384ULL,	// level_1
};

#define SIZES_QID_HASHMAP 50994ULL
#define SIZES_QID_INDEX 27034ULL
#define SIZES_ZSTD_DICTIONARY 131072ULL

#endif // DATABASE_CONSTANTS_H
