// AUTO-GENERATED BY RUST GENERATOR
// DO NOT EDIT MANUALLY

#ifndef DATABASE_CONSTANTS_H
#define DATABASE_CONSTANTS_H

#include <stdint.h>

// =========================================
// OFFSETS
// =========================================
#define OFFSETS_CONTENT 6887279804
#define OFFSETS_METADATA 41034688216

static const uint64_t OFFSETS_OMNI_SEARCH_LEVEL[] = {
    0,	// level_0
    4351956224,	// level_1
    4368956032,	// level_2
    4369022464,	// level_3
};

#define OFFSETS_QID_HASHMAP 4369022752
#define OFFSETS_QID_INDEX 5211782134
#define OFFSETS_ZSTD_DICTIONARY 48422742065

// =========================================
// OMNI_SEARCH
// =========================================
#define OMNI_SEARCH_CHUNK_SIZE_ROWS 256
#define OMNI_SEARCH_NUM_SPARSE_LEVELS 3
#define OMNI_SEARCH_TERM_SIZE 24
#define OMNI_SEARCH_TOP_LEVEL_ROWS 9
#define OMNI_SEARCH_TOTAL_ROW_SIZE 32

#endif // DATABASE_CONSTANTS_H
