#ifndef TEMPUS_H
#define TEMPUS_H

#include <stdio.h>
#include <inttypes.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Represents a decoded date, preserving historical and BC (Before Christ) dates.
 */
typedef struct {
    int64_t year;  /**< The year, can be negative for dates BC (e.g., -500 for 500 BC). */
    uint8_t month; /**< The month of the year (1-12). */
    uint8_t day;   /**< The day of the month (1-31). */
} TemporalDate;

/**
 * @brief Encodes an ISO-8601 date string into a sortable 64-bit integer.
 * 
 * This function expects a string starting with a sign (+ or -), matching 
 * the standard format provided by Wikidata (e.g., "+1969-07-20" or "-0500-01-01").
 * The resulting integer is formatted as (Year * 10000) + (Month * 100) + Day,
 * which perfectly preserves chronological sorting even for negative years.
 * 
 * @param iso_str Pointer to a null-terminated ISO date string.
 * @return A chronologically sortable int64_t representing the date, 
 *         or -1 if the string is NULL or malformed.
 */
int64_t temporal_encode(const char* iso_str);

/**
 * @brief Decodes a sortable 64-bit integer back into a TemporalDate structure.
 * 
 * @param code The sortable integer date generated by temporal_encode().
 * @param out_date Pointer to a TemporalDate struct where the result will be written.
 * @return true if successfully decoded, false if out_date is NULL.
 */
bool temporal_decode(int64_t code, TemporalDate* out_date);

#ifdef __cplusplus
}
#endif

#endif //TEMPUS_H
